### ISSUE TITLE
I've just try your component, but when I import *import VueBingMaps from 'vue-bing-maps';* I got bug can't load vue-bing-maps. Could you please help me to use it?

### ISSUE THREAD

**Issue by ngochai84** [ksullivan1856/vue-bing-maps#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ksullivan1856** [comment]
I messed up when creating the package.json file as the main property does not correctly map to the main entry point of the build module.  I will push an update to fix this shortly.

**Comment by ngochai84** [comment]
Oh, thanks you so much, i’m not pro with vue
